### ISSUE TITLE
Fix: Update the sandiego.org web scraper to add event metadata

### ISSUE THREAD

**Issue by mnich0ls** [mnich0ls/evee-sd#10]
The [sandiego.org web scraper](https://github.com/mnich0ls/evee-sd/issues/1) should add some missing metadata to events each time it runs. See the [Event Attributes](https://github.com/mnich0ls/evee-sd/wiki/Event-Attributes) for a summary of the metadata that should be included.

**Comment by jremi** [comment]
Please let me know if this would be acceptable JSON object format: 

```json
{
    "event": {
        "category": "",
        "location": "",
        "price": "",
        "dates": {
            "start_date": "",
            "end_date": ""
        },
        "time": "",
        "thumbnail_url": "",
        "detail_url": "",
        "source_url": "",
        "metadata": {
            "date_scraped": "",
            "status": "",
            "quality_rating": "",
            "original_": {
                "dates": ""
            }
        }
    }
}
```

**Comment by mnich0ls** [comment]
Looks good to me. How about ‘original_values’ instead of ‘original_’?

**Comment by jremi** [comment]
> Looks good to me. How about ‘original_values’ instead of ‘original_’?
> […](#)
> On Mar 14, 2019, at 1:57 AM, jremi ***@***.***> wrote: Please let me know if this would be acceptable JSON object format: { "event": { "category": "", "location": "", "price": "", "dates": { "start_date": "", "end_date": "" }, "time": "", "thumbnail_url": "", "detail_url": "", "source_url": "", "metadata": { "date_scraped": "", "status": "", "quality_rating": "", "original_": { "dates": "" } } } } — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

yes makes sense. will update to reflect that

**Comment by mnich0ls** [comment]
👍
