### ISSUE TITLE
Infrastructure: Event scrapers (event aggregators) deployment

### ISSUE THREAD

**Issue by mnich0ls** [mnich0ls/evee-sd#16]
Create a DO droplet for all web scrapers that use a similar framework i.e. all web scrapers written by @jremi use the same language and have similar dependencies and to me it makes sense to deploy on the same server (but I'm open to other/better ways!)

Create a deployment script (or use a deployment framework so that we can easily deploy changes to the scrapers/aggregators). 

Configure these scrapers to run in the early morning, but ensure that the frequency and time can be quickly changed if/when it becomes necessary.

**Comment by jremi** [comment]
All of this will be most likely related to the **_Evee - Transformation and Load Services_** google drive doc.
