### ISSUE TITLE
Infrastructure: UI deployment

### ISSUE THREAD

**Issue by mnich0ls** [mnich0ls/evee-sd#17]
Create a DO droplet to host the UI. Create a deployment script or use a deployment framework to ensure the UI can be updated with changes as necessary. 

(Note: please comment on this issue with required DNS changes to point the evee-sd.com domain at this new server once it's ready. )

**Comment by jremi** [comment]
I am getting started on this. I am just trying to evaluate the best deployment platform/environment. Original idea was to host via DO... however now I'm possibly reviewing using the AWS Amplify service.

**Comment by jremi** [comment]
AWS Amplify + Vue is a match made in heaven.

Just ran a deployment to Amazon:
![image](https://user-images.githubusercontent.com/5322988/56086244-55df7280-5e07-11e9-9767-a655b26b734a.png)

Live url: 
https://master.d2iro3z6pcc2i3.amplifyapp.com/

**Comment by jremi** [comment]
Related to the domain name.... We can point this to the AWS once you are ready. You will need AWS account. I currently have tested against my own personal AWS account.
