### ISSUE TITLE
Event Tranformation Service

### ISSUE THREAD

**Issue by mnich0ls** [mnich0ls/evee-sd#19]
An HTTP API that accepts raw events from EASs (Event Aggregator Services) setup to work/deploy/test on AWS

For it's initial POST endpoint (name TBD), the post body should be:

title 
source (e.g. meetup.com)
price
start_date
end_date
location
description
thumbnail_url
category
details_url (url that takes the user to the details page on the source site)

At the minimum, this service needs to standardize the dates so that events can be sorted in chronological order. In the future, this service will handle other transformation and standardization tasks.

After each event is processed, it should be pushed to the AWS SQS Queue System

**Comment by jremi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [mnich0ls/evee-sd/issues/19](https://trello.com/c/lAmIwnHe/1-mnich0ls-evee-sd-issues-19)

**Comment by jremi** [comment]
@mnich0ls What are the currently accepted ```category``` values and also accepted ```source``` values that the API v1 will currently allow?

**Comment by jremi** [comment]
Ok I just finished this `/api/v1/events/create` resource built and wrote out validation request body parameter / value checking. In addition did initial deployment setup of AWS EC2 instance + AWS SQS 

I need to commit this, but I think maybe to a separate repo. Let me know.

**Comment by mnich0ls** [comment]
Awesome. Regarding the category validation, I'm not worried about that right now. I see this service as handling any sort of normalization of categories rather than pushing that responsibility to the aggregators.

**Comment by jremi** [comment]
**Commited**: https://github.com/mnich0ls/evee-sd/commit/189d2891d99a2967747dcef177e004afc60b92f9
