### ISSUE TITLE
Events Loader

### ISSUE THREAD

**Issue by mnich0ls** [mnich0ls/evee-sd#21]
The v1 implementation of the events loader processes and moves events from the queue to the live database. The requirements are: 

1. Configure a database (AWS RDS - MySQL).
1. Configurable run time. This service should be easily triggered or configured to run at any specified time. 
1. Push events into the database with an initial status of `inactive`. When this process has emptied the queue of all events, it should set the state of currently `active` events to `archived`, then set any `inactive` events (i.e. all the newly added events) to `active`.  (Alternatively we could simply delete all events from the database when this process starts and repopulate with all the events from the queue).

**Comment by jremi** [comment]
SimpleDB is unofficially deprecated and Amazon prefers us to use DynamoDB.

**Comment by mnich0ls** [comment]
Ah I see. That explains why I didn’t see it when I was originally reviewing their database options.

**Comment by jremi** [comment]
☑️ Configure a database (AWS RDS - MySQL).

**Comment by jremi** [comment]
☑️ Configurable run time. This service should be easily triggered or configured to run at any specified time. (Configured for 1:00 AM Daily - California time)

**Comment by jremi** [comment]
☑️ Push events into the database 

https://github.com/mnich0ls/evee-sd/commit/c2b65f017e06c0a8e083b05ab2938056ed07ac56
