### ISSUE TITLE
Remove sensitive data from repo

### ISSUE THREAD

**Issue by mnich0ls** [mnich0ls/evee-sd#22]
Let's remove any references to our IPs/servers or other sensitive info and make them environment variables where possible.

**Comment by jremi** [comment]
I already moved all api keys to external config files on server... but yes
I will remove endpoints from repo also

**Comment by mnich0ls** [comment]
Perfect.

**Comment by jremi** [comment]
Moved this to a server configs folder that is used with tiny shell script to install the servers private config settings into all corresponding directories.
