### ISSUE TITLE
Public Events API

### ISSUE THREAD

**Issue by mnich0ls** [mnich0ls/evee-sd#23]
Create the public events API that the UI will use to display events. 

1. Configure DynamoDB
1. All events should be returned in chronological order by default.
1. For now we will return the full set of events.

**Comment by jremi** [comment]
https://github.com/mnich0ls/evee-sd/commit/99249e1f4841250c72df7a10b4cd8817c87aa9a8

**Comment by jremi** [comment]
Note for Github reference we opted to use AWS RDS with MySQL.
