### ISSUE TITLE
Update and deploy Events UI

### ISSUE THREAD

**Issue by mnich0ls** [mnich0ls/evee-sd#24]
Update the Events UI to use the new Events API and deploy to AWS. 

No need to worry about setting up DNS yet, let's just use the default host that AWS provides until we get the remaining MVP tasks complete.

**Comment by jremi** [comment]
☑️ Migrated/updated

https://github.com/mnich0ls/evee-sd-ui/commit/7d046c585d034e2b541480f643525c1aaf83c5d3
