### ISSUE TITLE
Update and deploy meetup.com and sandiego.org aggregators

### ISSUE THREAD

**Issue by mnich0ls** [mnich0ls/evee-sd#25]
Update both completed aggregators to use the new Event Create API, deploy, and schedule each to run once a day.

**Comment by jremi** [comment]
- Migrating both of the existing aggregators to use the new Event Create API POST method
- Deploying (either EC2 and/or Lambda ... need to evaluate, probably on EC2)
- Setup cron scheduling for aggregators to run at set time 1x daily.

**Comment by jremi** [comment]
☑ Migrating both of the existing aggregators to use the new Event Create API POST method 

https://github.com/mnich0ls/evee-sd/commit/f784aca72bd1db73957ce2181ef9c91843f828a3

**Comment by jremi** [comment]
☑ Deploying (either EC2 and/or Lambda ... need to evaluate, probably on EC2)
https://github.com/mnich0ls/evee-sd/commit/6c28971bc18485b0f4b33da07b52e6087fc54873

**Comment by jremi** [comment]
☑ Deployed (EC2 with pm2)

<img src="https://i.imgur.com/oGjJYcU.png" />
