### ISSUE TITLE
Eventbrite indexer

### ISSUE THREAD

**Issue by mnich0ls** [mnich0ls/evee-sd#26]
Create an Eventbrite indexer use the Eventbrite API. This indexer should be scheduled to run nightly like the others. Please ensure the actual Eventbrite categories are used e.g. Music, Food, etc. instead of grouping this under a single category i.e. Eventbrite.

**Comment by jremi** [comment]
https://github.com/mnich0ls/evee-sd/commit/9a6d7fcb8d9a7f4e1c20954ff6471a4b11d7da42
