### ISSUE TITLE
Parse event location zip code

### ISSUE THREAD

**Issue by mnich0ls** [mnich0ls/evee-sd#27]
* Modify the API (EventGet and EventCreate) to have the new additional field zip_code
* Modify the db to have the new column zip_code (if no zip null)
* Update indexers (where zip code) available to send the zip code to the API 

Note: sd.org known to not have zip, but they do have accurate neighborhood information already that we are currently utilizing

**Comment by jremi** [comment]
Need to deploy and run final tets.
