### ISSUE TITLE
Indexer - San Diego Reader

### ISSUE THREAD

**Issue by mnich0ls** [mnich0ls/evee-sd#28]
Create an indexer for the San Diego Reader: https://www.sandiegoreader.com/events/search/

It appears they have sufficient location information (i.e. neighborhood) that we do not need the zip code.

Since we need to page through each search result, we will only index events within the next 30 days. Each page of search results will trigger a request to get additional data about the event e.g. thumbnail, cost, time, etc.

**Comment by jremi** [comment]
https://github.com/mnich0ls/evee-sd/commit/4d4dae3e38cb53d6de7ab51a2270c0414eafbb33
